---
- hosts: localhost
  become: yes

  tasks:
  - name: Fix caps lock
    lineinfile:
      path: /etc/default/keyboard
      line: XKBOPTIONS="ctrl:nocaps"
  - name: Install autologin
    copy:
      src: files/01_username.conf
      dest: /etc/lightdm/lightdm.conf.d/01_username.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
      
